server:
  port: 8080

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:sentinelops}
    password: ${SPRING_DATASOURCE_PASSWORD:sentinelops}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  delay-ms: ${PAYMENT_DELAY_MS:0}
  decline-rate: ${PAYMENT_DECLINE_RATE:0.0}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
