apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecretName }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
